# Site settings
author: Apocalypse
title: Apocalypse Blog
SEOTitle: 小小小罗的博客 | Apocalypse Blog
header-img: img/tag-bg.jpg
post-img: assets/img/post-bg.jpg
email: imlfhhh@gmail.com
description: "Software & BigData Engineer, F1 Noob Lover"
keyword: "Java & Big Data & Spark & F1 & NBA"
baseurl: 
# url: "https://www.kasmine.cn" # your host, for absolute URL
# baseurl: "" # 本地调试使用
# imgurl: "/assets/img"

# Basic settings

# 添加sass
# @see http://markdotto.com/2014/09/25/sass-and-jekyll/
sass: 
  sass_dir: _scss
  # style: compressed


# SNS settings
RSS: false
weibo_username:     Apocalypsey
# zhihu_username: kasmine
github_username:    Apocalypsey
#twitter_username: kasmine
facebook_username:  kasmineLiao
# linkedin_username: firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
# permalink: pretty
permalink: /:year/:month/:day/:title.html
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # 如何设置

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Analytics settings TODO:
# Google Analytics
ga_track_id: 'UA-89922034-1'            # Format: UA-xxxxxx-xx
# ga_domain:

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "认真学习 n(*≧▽≦*)n <br />拥抱大数据 "
sidebar-avatar: img/about-bg-walle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Catalog settings
catalog: true

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true